[package]
name = "pocket-api"
version = "0.1.0"
authors = ["Jesper Håkansson <jesper@jesperh.se>"]

[dependencies]
failure = "0.1.2"
futures = "0.1.23"
serde = "1.0.71"
serde_json = "1.0.24"
serde_derive = "1.0.71"
httper = { path = "../../httper" }
